name: zstd_native
description: 'Native implementation of the zstd plugin.'
version: 0.0.1-dev.1
repository: https://github.com/yanshouwang/zstd
issue_tracker: https://github.com/yanshouwang/zstd/issues
topics:
  - zstd

environment:
  sdk: ^3.7.2
  # Flutter versions prior to 3.7 did not support the
  # sharedDarwinSource option.
  flutter: '>=3.7.0'
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  zstd_api: ^0.0.1-dev.1
  ffi: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  ffigen: ^19.0.0

flutter:
  plugin:
    implements: zstd
    platforms:
      android:
        ffiPlugin: true
        dartPluginClass: ZstdNativePlugin
      ios:
        ffiPlugin: true
        sharedDarwinSource: true
        dartPluginClass: ZstdNativePlugin
      macos:
        ffiPlugin: true
        sharedDarwinSource: true
        dartPluginClass: ZstdNativePlugin
      windows:
        ffiPlugin: true
        dartPluginClass: ZstdNativePlugin
      linux:
        ffiPlugin: true
        dartPluginClass: ZstdNativePlugin
