name: zstd_api
description: 'A common platform interface for the zstd plugin.'
version: 0.0.1-dev.0
repository: https://github.com/yanshouwang/zstd
issue_tracker: https://github.com/yanshouwang/zstd/issues
topics:
  - zstd

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
