name: zstd
description: >-
  Zstandard, or zstd as short version, is a fast lossless compression algorithm,
  targeting real-time compression scenarios at zlib-level and better compression ratios.
  It's backed by a very fast entropy stage, provided by Huff0 and FSE library.
version: 0.0.1-dev.1
repository: https://github.com/yanshouwang/zstd
issue_tracker: https://github.com/yanshouwang/zstd/issues
topics:
  - zstd

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  zstd_api: ^0.0.1-dev.1
  zstd_native: ^0.0.1-dev.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: zstd_native
      ios:
        default_package: zstd_native
      macos:
        default_package: zstd_native
      windows:
        default_package: zstd_native
      linux:
        default_package: zstd_native
